"use client";

import { useState, useEffect } from "react";
import Link from "next/link";
import { motion, AnimatePresence } from "framer-motion";
import { useBonanzaGame } from "../hooks/useBonanzaGame";
import { setSoundMuted, unlockAudio } from "../sounds/soundEngine";
import { StatsPanel } from "./StatsPanel";
import { AutoSpinControls } from "./AutoSpinControls";
import { GameGrid } from "./GameGrid";
import { MobileBetSheet } from "./MobileBetSheet";
import { CandyWorldBackground } from "./CandyWorldBackground";
import { WinOverlay } from "./WinOverlay";
import { ScreenEffects } from "./ScreenEffects";
import { FreeSpinsCinematic } from "./FreeSpinsCinematic";
import { BET_OPTIONS } from "../types";

export function BonanzaGame() {
  const game = useBonanzaGame();
  const [sheetOpen, setSheetOpen] = useState(false);
  const [statsOpen, setStatsOpen] = useState(false);
  const [doubleChanceActive, setDoubleChanceActive] = useState(false);

  useEffect(() => {
    const unlock = () => {
      unlockAudio();
    };
    window.addEventListener("click", unlock);
    window.addEventListener("touchstart", unlock);
    return () => {
      window.removeEventListener("click", unlock);
      window.removeEventListener("touchstart", unlock);
    };
  }, []);

  const spinning = game.phase !== "idle" && game.phase !== "freeSpinsIntro";
  const disabled = spinning;

  // Active bet increases by 25% if Double Chance is active (matches Sweet Bonanza logic)
  const displayBet = doubleChanceActive ? game.bet * 1.25 : game.bet;

  const toggleMute = () => {
    game.setMuted(!game.muted);
    setSoundMuted(!game.muted);
  };

  const handleNextBet = () => {
    if (disabled) return;
    const idx = BET_OPTIONS.indexOf(game.bet as any);
    if (idx < BET_OPTIONS.length - 1) game.setBet(BET_OPTIONS[idx + 1]);
  };

  const handlePrevBet = () => {
    if (disabled) return;
    const idx = BET_OPTIONS.indexOf(game.bet as any);
    if (idx > 0) game.setBet(BET_OPTIONS[idx - 1]);
  };

  return (
    <div className="relative flex min-h-dvh flex-col overflow-hidden text-zinc-100 pb-20 sm:pb-24">
      {/* Premium Candy Land animated background generated by Nano Banana */}
      <CandyWorldBackground />

      <ScreenEffects shake={game.screenShake} flash={game.screenFlash}>
        {/* Top Header */}
        <header className="relative z-20 flex items-center justify-between border-b border-white/[0.05] bg-black/35 px-4 py-2.5 backdrop-blur-2xl sm:px-6">
          <div className="flex items-center gap-3">
            <Link
              href="/"
              className="flex items-center gap-1.5 rounded-xl border border-white/[0.08] bg-white/[0.03] px-3 py-1.5 text-xs font-semibold text-zinc-400 transition hover:border-pink-400/30 hover:text-white"
            >
              <svg className="w-3.5 h-3.5" fill="none" stroke="currentColor" strokeWidth="2" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" d="M15 19l-7-7 7-7" /></svg>
              Oyunlar
            </Link>
            <div className="hidden sm:block h-5 w-px bg-white/[0.06]" />
            <div className="hidden sm:block">
              <p className="text-[9px] font-bold uppercase tracking-[0.32em] text-pink-300/70 leading-none">
                Şeker Patlaması
              </p>
              <h2 className="bg-gradient-to-r from-pink-200 via-fuchsia-200 to-violet-200 bg-clip-text text-sm font-bold text-transparent">
                Bonanza Pro
              </h2>
            </div>
          </div>

          {/* Free Spins Left Indicator */}
          {game.inFreeSpins && (
            <motion.div
              initial={{ scale: 0.8, opacity: 0 }}
              animate={{ scale: 1, opacity: 1 }}
              className="rounded-2xl border-2 border-amber-400/50 bg-gradient-to-b from-amber-500/25 to-amber-600/10 px-4 py-1 text-center shadow-lg"
            >
              <p className="text-[9px] font-bold uppercase tracking-wider text-amber-200/80 leading-none">FREE SPIN</p>
              <p className="font-money text-lg font-bold text-amber-300 leading-tight">{game.freeSpinsLeft}</p>
            </motion.div>
          )}

          <div className="flex items-center gap-2">
            <button
              onClick={() => setStatsOpen(true)}
              className="rounded-xl border border-white/[0.06] bg-white/[0.03] px-3 py-1.5 text-xs font-semibold text-zinc-400 transition hover:bg-white/[0.06] hover:text-white"
            >
              İstatistik
            </button>
            <button
              onClick={game.resetBalance}
              className="rounded-xl border border-pink-500/15 bg-pink-500/8 px-3 py-1.5 text-xs font-semibold text-pink-400 transition hover:bg-pink-500/15"
            >
              Sıfırla
            </button>
          </div>
        </header>

        {/* Main Game Screen */}
        <div className="relative z-10 mx-auto flex w-full max-w-[1440px] flex-1 flex-col items-center justify-center px-4 py-4 sm:px-6 lg:px-8">
          <div className="flex flex-col items-center justify-center gap-6 lg:flex-row lg:items-start lg:gap-10 xl:gap-14 w-full">
            
            {/* LEFT COLUMN: Buy Feature & Double Chance (Hidden on mobile header, shown in flex layout) */}
            <div className="flex flex-row flex-wrap justify-center gap-4 lg:flex-col lg:w-48 lg:shrink-0 lg:gap-5">
              {/* BUY FEATURE BOX (Sweet Bonanza Pink Candy box) */}
              <motion.div
                whileHover={{ scale: 1.03 }}
                className="relative flex flex-col items-center justify-between w-40 sm:w-44 rounded-[1.75rem] border-4 border-yellow-400 bg-gradient-to-b from-pink-500 via-pink-600 to-fuchsia-700 p-3 text-center shadow-2xl select-none"
              >
                <div className="absolute inset-0 bg-[radial-gradient(circle_at_50%_0%,rgba(255,255,255,0.25),transparent_60%)] pointer-events-none rounded-[1.5rem]" />
                <p className="text-[10px] font-black tracking-wider text-yellow-300 uppercase leading-none drop-shadow-[0_2px_2px_rgba(0,0,0,0.6)]">
                  ÖZELLİK SATIN AL
                </p>
                <p className="text-[9px] font-bold text-pink-100 uppercase tracking-tight mt-0.5">
                  FREE SPIN
                </p>
                <button
                  onClick={() => void game.buyFeature()}
                  disabled={game.balance < game.bet * 100 || disabled || game.inFreeSpins}
                  className="mt-2.5 w-full rounded-2xl bg-gradient-to-b from-amber-300 to-yellow-500 hover:from-amber-200 hover:to-yellow-400 py-2.5 font-black text-purple-950 text-sm shadow-[0_4px_12px_rgba(0,0,0,0.3)] border border-white/30 transition hover:brightness-110 active:scale-95 disabled:opacity-60 disabled:pointer-events-none"
                >
                  {game.formatCoins(game.bet * 100)}
                </button>
              </motion.div>

              {/* BET DOUBLE CHANCE BOX (Sweet Bonanza Green Candy box) */}
              <motion.div
                whileHover={{ scale: 1.03 }}
                className="relative flex flex-col items-center justify-between w-40 sm:w-44 rounded-[1.75rem] border-4 border-emerald-400 bg-gradient-to-b from-emerald-500 via-emerald-600 to-teal-700 p-3 text-center shadow-2xl select-none"
              >
                <div className="absolute inset-0 bg-[radial-gradient(circle_at_50%_0%,rgba(255,255,255,0.25),transparent_60%)] pointer-events-none rounded-[1.5rem]" />
                <p className="text-[11px] font-black tracking-wider text-yellow-200 uppercase leading-none drop-shadow-[0_2px_2px_rgba(0,0,0,0.6)]">
                  BAHİS
                </p>
                <p className="font-money text-base font-black text-white leading-tight mt-0.5">
                  {game.formatCoins(displayBet)}
                </p>
                <div className="my-1.5">
                  <p className="text-[8px] font-extrabold text-emerald-100 uppercase tracking-tighter leading-none">
                    ÖZELLİK KAZANMA ŞANSI
                  </p>
                  <p className="text-[9px] font-black text-yellow-300 uppercase tracking-tight leading-normal">
                    İKİ KAT DAHA FAZLA
                  </p>
                </div>
                
                {/* Custom Toggle Switch */}
                <button
                  onClick={() => setDoubleChanceActive(!doubleChanceActive)}
                  disabled={disabled}
                  className={`relative flex h-7 w-16 items-center rounded-full px-1 shadow-[inset_0_2px_5px_rgba(0,0,0,0.4)] border border-emerald-300/40 transition-colors duration-300 ${
                    doubleChanceActive ? "bg-emerald-300" : "bg-black/45"
                  }`}
                >
                  <span className="absolute left-2 text-[8px] font-black text-emerald-950" style={{ display: doubleChanceActive ? "block" : "none" }}>AÇIK</span>
                  <span className="absolute right-2 text-[8px] font-black text-zinc-400" style={{ display: doubleChanceActive ? "none" : "block" }}>KAPALI</span>
                  <motion.div
                    layout
                    className="h-5 w-5 rounded-full bg-white shadow-md border border-zinc-200"
                    animate={{ x: doubleChanceActive ? 32 : 0 }}
                    transition={{ type: "spring", stiffness: 500, damping: 30 }}
                  />
                </button>
              </motion.div>
            </div>

            {/* MIDDLE COLUMN: Game Grid and Title Logo */}
            <div className="flex flex-col items-center gap-4 py-2 flex-1 max-w-[560px] w-full">
              {/* Sweet Bonanza 3D Bubble Text Logo */}
              <div className="relative mb-1 flex flex-col items-center justify-center select-none filter drop-shadow-[0_6px_10px_rgba(0,0,0,0.6)] animate-pulse">
                <div className="flex items-center gap-1.5 font-black text-center" style={{ fontFamily: "'Arial Black', sans-serif" }}>
                  <span style={{
                    fontSize: "36px",
                    background: "linear-gradient(to bottom, #ffffff, #ffeb3b 50%, #f44336 100%)",
                    WebkitBackgroundClip: "text",
                    WebkitTextFillColor: "transparent",
                    WebkitTextStroke: "2px #4a148c",
                    letterSpacing: "-1.5px"
                  }}>
                    SWEET
                  </span>
                  <span style={{
                    fontSize: "36px",
                    background: "linear-gradient(to bottom, #ffffff, #ff4081 50%, #7c4dff 100%)",
                    WebkitBackgroundClip: "text",
                    WebkitTextFillColor: "transparent",
                    WebkitTextStroke: "2px #4a148c",
                    letterSpacing: "-1.5px"
                  }}>
                    BONANZA
                  </span>
                </div>
              </div>

              {/* Win overlay for big/mega wins */}
              <WinOverlay
                amount={game.liveWin}
                visible={game.liveWin > 0 && game.phase !== "idle"}
                multiplier={game.lastMultiplier}
                showMultiplier={game.showMultiplier}
                celebrationMessage={game.winBanner}
                formatCoins={game.formatCoins}
              />

              {/* The Game Grid with Candy Cane border */}
              <GameGrid
                grid={game.grid}
                activeWins={game.activeWins}
                phase={game.phase}
                cascadeMeta={game.cascadeMeta}
                speedMode={game.speedMode}
              />
            </div>

            {/* RIGHT COLUMN: Auto Spins Panel (Desktop only) */}
            <div className="hidden lg:flex lg:flex-col lg:w-60 xl:w-72 lg:shrink-0 lg:gap-4">
              <div className="rounded-[2rem] border border-white/10 bg-black/40 p-4 backdrop-blur-md shadow-2xl">
                <h3 className="text-xs font-bold text-pink-300 uppercase tracking-wider mb-3">Otomatik Spin</h3>
                <AutoSpinControls
                  speedMode={game.speedMode}
                  setSpeedMode={game.setSpeedMode}
                  autoSpin={game.autoSpin}
                  autoRemaining={game.autoRemaining}
                  startAuto={game.startAuto}
                  stopAuto={game.stopAuto}
                  disabled={disabled}
                />
              </div>

              <div className="rounded-[2rem] border border-white/10 bg-black/40 p-4 backdrop-blur-md shadow-2xl">
                <h3 className="text-xs font-bold text-pink-300 uppercase tracking-wider mb-2">Ayarlar</h3>
                <div className="flex flex-col gap-2">
                  <button
                    type="button"
                    onClick={toggleMute}
                    className="w-full rounded-xl border border-white/10 bg-white/[0.04] py-2.5 text-xs text-zinc-300 hover:bg-white/[0.08]"
                  >
                    {game.muted ? "Sesi aç" : "Sesi kapat"}
                  </button>
                  <button
                    type="button"
                    onClick={() => setSheetOpen(true)}
                    className="w-full rounded-xl border border-pink-500/20 bg-pink-500/10 py-2.5 text-xs text-pink-300 hover:bg-pink-500/20"
                  >
                    Hızlı Bahis Seçenekleri
                  </button>
                </div>
              </div>
            </div>
          </div>
        </div>
      </ScreenEffects>

      {/* FREE SPINS INTRO CINEMATIC */}
      <AnimatePresence>
        {game.fsIntro && (
          <FreeSpinsCinematic
            spins={game.fsIntro.spins}
            multBoost={game.fsIntro.multBoost}
            onComplete={game.completeFsIntro}
          />
        )}
      </AnimatePresence>

      {/* MOBILE STATS OVERLAY DIALOG */}
      {statsOpen && (
        <div className="fixed inset-0 z-50">
          <div className="absolute inset-0 bg-black/85 backdrop-blur-md" onClick={() => setStatsOpen(false)} />
          <div className="absolute inset-x-4 top-[10%] max-h-[75dvh] overflow-y-auto rounded-3xl border border-white/10 bg-[#1c072b]/95 p-6 shadow-2xl">
            <div className="flex items-center justify-between mb-4">
              <h3 className="text-lg font-black text-pink-200">İstatistikler & Geçmiş</h3>
              <button onClick={() => setStatsOpen(false)} className="text-2xl text-zinc-500 hover:text-white">×</button>
            </div>
            <StatsPanel
              stats={game.stats}
              derived={game.derived}
              history={game.history}
              formatCoins={game.formatCoins}
            />
          </div>
        </div>
      )}

      {/* MOBILE SPEED & AUTO CONTROLS SHEET */}
      <MobileBetSheet
        open={sheetOpen}
        onClose={() => setSheetOpen(false)}
        bet={game.bet}
        setBet={game.setBet}
        speedMode={game.speedMode}
        setSpeedMode={game.setSpeedMode}
        autoSpin={game.autoSpin}
        autoRemaining={game.autoRemaining}
        startAuto={game.startAuto}
        stopAuto={game.stopAuto}
        disabled={disabled}
      />

      {/* ========================================================
          ULTRA PREMIUM bottom CONTROL BAR (PRAGMATIC PLAY STYLE) 
         ======================================================== */}
      <div className="fixed bottom-0 left-0 right-0 z-40 bg-gradient-to-t from-black via-black/85 to-black/70 border-t border-white/[0.08] backdrop-blur-xl px-4 py-3 sm:py-4 select-none flex items-center justify-between shadow-[0_-10px_35px_rgba(0,0,0,0.6)]">
        
        {/* LEFT CONTROLS: Settings, Sound, Info & CREDIT/BET Displays */}
        <div className="flex items-center gap-3 md:gap-5">
          {/* Quick Icons */}
          <div className="flex items-center gap-2 text-zinc-400 text-lg border-r border-white/10 pr-3 sm:pr-4">
            <button 
              onClick={() => setStatsOpen(true)}
              className="hover:text-white transition active:scale-90"
              title="İstatistikler"
            >
              ⚙️
            </button>
            <button 
              onClick={toggleMute} 
              className="hover:text-white transition active:scale-90"
              title={game.muted ? "Sesi Aç" : "Sesi Kapat"}
            >
              {game.muted ? "🔇" : "🔊"}
            </button>
            <button 
              onClick={() => setStatsOpen(true)}
              className="hover:text-white transition active:scale-90"
              title="Bilgi"
            >
              ℹ️
            </button>
          </div>
          
          {/* Credit and Bet Info Boxes */}
          <div className="flex items-center gap-3 sm:gap-6 text-xs">
            <div>
              <p className="text-[8px] font-black text-zinc-500 uppercase tracking-wider leading-none">BAKİYE</p>
              <p className="font-money text-emerald-300 font-extrabold text-sm sm:text-base mt-0.5">
                {game.formatCoins(game.balance)}
              </p>
            </div>
            <div>
              <p className="text-[8px] font-black text-zinc-500 uppercase tracking-wider leading-none">BAHİS</p>
              <p className="font-money text-pink-200 font-extrabold text-sm sm:text-base mt-0.5">
                {game.formatCoins(displayBet)}
              </p>
            </div>
          </div>
        </div>

        {/* MIDDLE CONTROL: WIN amount box with gold details */}
        <div className="flex-1 max-w-[140px] sm:max-w-[240px] md:max-w-[320px] mx-2 sm:mx-4">
          <div className="bg-black/50 border border-yellow-500/25 rounded-2xl py-1 sm:py-1.5 px-3 shadow-[inset_0_2px_8px_rgba(0,0,0,0.7)] text-center">
            <p className="text-[8px] font-black text-zinc-500 uppercase tracking-wider leading-none">KAZANÇ</p>
            <p className="font-money text-sm sm:text-lg font-black text-yellow-400 drop-shadow-[0_2px_4px_rgba(0,0,0,0.5)] mt-0.5">
              {game.liveWin > 0 
                ? game.formatCoins(game.liveWin) 
                : (game.lastWin > 0 ? game.formatCoins(game.lastWin) : "—")
              }
            </p>
          </div>
        </div>

        {/* RIGHT CONTROLS: Bet Adjust, Spin Button, Autoplay */}
        <div className="flex items-center gap-3 md:gap-4">
          {/* Bet Adjuster (+ / -) */}
          <div className="hidden sm:flex items-center bg-black/45 rounded-2xl border border-white/10 p-0.5">
            <button 
              onClick={handlePrevBet}
              disabled={disabled}
              className="w-7 h-7 flex items-center justify-center font-black text-white/60 hover:text-white disabled:opacity-30 active:scale-95 transition"
              title="Bahsi Azalt"
            >
              -
            </button>
            <span className="font-money px-2 text-[11px] text-zinc-300 font-black min-w-[44px] text-center">
              {game.bet >= 1000 ? `${game.bet / 1000}K` : game.bet}
            </span>
            <button 
              onClick={handleNextBet}
              disabled={disabled}
              className="w-7 h-7 flex items-center justify-center font-black text-white/60 hover:text-white disabled:opacity-30 active:scale-95 transition"
              title="Bahsi Artır"
            >
              +
            </button>
          </div>

          {/* SPIN & AUTO CONTROLS WRAPPER */}
          <div className="flex items-center gap-2">
            {/* Mobile-only settings trigger sheet */}
            <button
              onClick={() => setSheetOpen(true)}
              className="sm:hidden w-8 h-8 rounded-full bg-white/5 border border-white/10 flex items-center justify-center text-xs"
              title="Bahis Düzenle"
            >
              ⚙️
            </button>

            {/* Spin button wrapper */}
            <div className="relative flex items-center justify-center">
              <button
                onClick={() => void game.spin()}
                disabled={!game.canSpin}
                className={`relative w-12 h-12 sm:w-14 sm:h-14 rounded-full flex items-center justify-center shadow-lg transition-transform active:scale-90 disabled:opacity-50 disabled:pointer-events-none ${
                  spinning 
                    ? "bg-pink-600 cursor-not-allowed" 
                    : "bg-gradient-to-b from-yellow-300 to-amber-500 hover:from-yellow-200 hover:to-amber-400 border-2 border-white/80"
                }`}
              >
                {spinning ? (
                  <svg className="animate-spin h-5 w-5 text-white" fill="none" viewBox="0 0 24 24">
                    <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
                    <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z" />
                  </svg>
                ) : (
                  <span className="text-purple-950 font-black text-xl sm:text-2xl leading-none">↻</span>
                )}
              </button>
            </div>
          </div>
        </div>

      </div>
    </div>
  );
}
