"use client";

import { motion } from "framer-motion";

export function CandyWorldBackground() {
  return (
    <div className="pointer-events-none absolute inset-0 overflow-hidden select-none">
      {/* High-res Candy background generated by Nano Banana */}
      <div 
        className="absolute inset-0 bg-cover bg-center bg-no-repeat"
        style={{
          backgroundImage: "url('/images/candy_background.png')",
        }}
      />
      
      {/* Animated soft color overlays for atmosphere */}
      <motion.div
        className="absolute inset-0 mix-blend-overlay"
        animate={{ opacity: [0.2, 0.4, 0.2] }}
        transition={{ duration: 8, repeat: Infinity, ease: "easeInOut" }}
        style={{
          background: "radial-gradient(circle at 50% 50%, #f472b6, transparent 65%)"
        }}
      />

      {/* Floating light fog at the bottom */}
      <motion.div
        className="absolute bottom-0 left-0 right-0 h-48 bg-gradient-to-t from-pink-300/15 to-transparent blur-xl"
        animate={{ y: [0, 8, 0] }}
        transition={{ duration: 12, repeat: Infinity, ease: "easeInOut" }}
      />
    </div>
  );
}
